### ISSUE TITLE
revertAnimation() callback not called (2.1.3)

### ISSUE THREAD

**Issue by Pegeot** [leandroBorgesFerreira/LoadingButtonAndroid#141]
Version: br.com.simplepass:loading-button-android:2.1.3

The callback _onAnimationEndListener_ passed by parameter to function revertAnimation is not being called.

**Comment by leandroBorgesFerreira** [comment]
fixed in version 2.1.5.

**Comment by MuriloCalegari** [comment]
@leandroBorgesFerreira, version 2.1.5 did not fix this issue

**Comment by MuriloCalegari** [comment]
Hi @leandroBorgesFerreira, is this going to be fixed? What is the procedure for debugging it?

**Comment by MuriloCalegari** [comment]
At:

```
internal fun applyAnimationEndListener(animator: Animator, onAnimationEndListener: () -> Unit) =
    animator.addListener(object : AnimatorListenerAdapter() {
        override fun onAnimationEnd(animation: Animator?) {
            onAnimationEndListener()
            animator.removeListener(this)
        }
    })
```

onAnimationEnd() is never called when it is supposed to be. But if I reclick the button after the animation has ended, then onAnimationEnd() is called and consequently onAnimationEndListener() works.
